name: build-and-deploy
on:
  push:
    branches: ["main"]

permissions:
  contents: read
  packages: write

jobs:
  kickoff-template:
    uses: tyreesamurai/ci-templates/.github/workflows/deploy.yml@main
    with:
      image_name: tyreesamurai/finance-management
      service_dir: /srv/apps/finance-management
    secrets: inherit
