name: build-and-deploy
on:
  push:
    branches: ["main"]

permissions:
  contents: read
  packages: write

jobs:
  kickoff-template:
    uses: tyreesamurai/ci-templates/.github/workflows/deploy.yml@main
    with:
      image_name: tyreesamurai/finances
      context: .
      dockerfile: Dockerfile
      namespace: finances
      deployment: finances
      kube_context: k3d-home
    secrets: inherit
